#!/bin/sh

mkdir -p tmp

# cc65 -Oi --add-source src/main.c -o tmp/main.s
cc65 --add-source src/main.c -o tmp/main.s
ca65 src/import_binary_files.s -o tmp/import_binary_files.o
ca65 tmp/main.s

ld65 -C nes.cfg -o game.nes tmp/import_binary_files.o tmp/main.o nes.lib
